const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const srcRoot = path.join(projectRoot, 'src');
const docsRoot = path.join(projectRoot, 'docs');

const ensureDir = (dir) => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
};

const read = (filePath) => fs.readFileSync(filePath, 'utf8');

const toPosix = (p) => p.replace(/\\/g, '/');

const parseMainRoutes = (fileContent) => {
  const varToPath = {};
  const requireRegex = /const\s+(\w+)\s*=\s*require\(['"](.+?)['"]\);/g;
  let match;

  while ((match = requireRegex.exec(fileContent)) !== null) {
    const varName = match[1];
    const importPath = match[2];
    varToPath[varName] = importPath;
  }

  const mounts = [];
  const mountRegex = /router\.use\(\s*['"](.+?)['"]\s*,\s*(\w+)\s*\)/g;
  while ((match = mountRegex.exec(fileContent)) !== null) {
    mounts.push({ basePath: match[1], routeVar: match[2] });
  }

  return { varToPath, mounts };
};

const parseRouteFileEndpoints = (content) => {
  const endpoints = [];
  const routeRegex = /router\.(get|post|put|patch|delete)\(\s*['"](.+?)['"]/g;
  let match;
  while ((match = routeRegex.exec(content)) !== null) {
    endpoints.push({
      method: match[1].toUpperCase(),
      routePath: match[2]
    });
  }
  return endpoints;
};

const joinPaths = (a, b) => {
  const left = a.endsWith('/') ? a.slice(0, -1) : a;
  const right = b.startsWith('/') ? b : `/${b}`;
  return `${left}${right}`.replace(/\/+/g, '/');
};

const resolveRouteFilePath = (mainRoutesPath, importPath) => {
  const resolved = path.resolve(path.dirname(mainRoutesPath), importPath);
  if (fs.existsSync(resolved)) return resolved;
  if (fs.existsSync(`${resolved}.js`)) return `${resolved}.js`;
  return null;
};

const buildEndpoints = () => {
  const routesPath = path.join(srcRoot, 'routes.js');
  const routesContent = read(routesPath);
  const { varToPath, mounts } = parseMainRoutes(routesContent);

  const output = [];

  for (const mount of mounts) {
    const importPath = varToPath[mount.routeVar];
    if (!importPath) continue;

    const routeFilePath = resolveRouteFilePath(routesPath, importPath);
    if (!routeFilePath) continue;

    const routeContent = read(routeFilePath);
    const endpoints = parseRouteFileEndpoints(routeContent);

    for (const ep of endpoints) {
      output.push({
        method: ep.method,
        path: joinPaths('/api', joinPaths(mount.basePath, ep.routePath)),
        module: path.basename(path.dirname(routeFilePath)),
        source: toPosix(path.relative(projectRoot, routeFilePath))
      });
    }
  }

  output.sort((a, b) => {
    if (a.path === b.path) return a.method.localeCompare(b.method);
    return a.path.localeCompare(b.path);
  });

  return output;
};

const generateMarkdown = (endpoints) => {
  const now = new Date().toISOString();
  const lines = [];

  lines.push('# API Endpoints (Auto-Generated)');
  lines.push('');
  lines.push(`Generated at: \`${now}\``);
  lines.push('');
  lines.push('| Method | Path | Module | Source |');
  lines.push('|---|---|---|---|');

  for (const ep of endpoints) {
    lines.push(`| \`${ep.method}\` | \`${ep.path}\` | \`${ep.module}\` | \`${ep.source}\` |`);
  }

  lines.push('');
  lines.push('> Do not edit this file manually. Run `npm run docs:generate`.');
  lines.push('');

  return lines.join('\n');
};

const generateOpenApiJson = (endpoints) => {
  const paths = {};
  for (const ep of endpoints) {
    const p = ep.path.replace('/api', '') || '/';
    if (!paths[p]) paths[p] = {};
    paths[p][ep.method.toLowerCase()] = {
      tags: [ep.module],
      summary: `${ep.method} ${ep.path}`,
      responses: {
        200: { description: 'Success' }
      }
    };
  }

  return {
    openapi: '3.0.3',
    info: {
      title: 'Mall Management API',
      version: '1.0.0',
      description: 'Auto-generated endpoint index. Complete docs are in /docs/api.'
    },
    servers: [{ url: '/api' }],
    paths
  };
};

const writeOutputs = (endpoints) => {
  const apiDocsDir = path.join(docsRoot, 'api');
  const openApiDir = path.join(docsRoot, 'openapi');
  ensureDir(apiDocsDir);
  ensureDir(openApiDir);

  fs.writeFileSync(
    path.join(apiDocsDir, 'endpoints.generated.md'),
    generateMarkdown(endpoints),
    'utf8'
  );

  fs.writeFileSync(
    path.join(openApiDir, 'openapi.generated.json'),
    JSON.stringify(generateOpenApiJson(endpoints), null, 2),
    'utf8'
  );
};

const main = () => {
  const endpoints = buildEndpoints();
  writeOutputs(endpoints);
  console.log(`Generated docs for ${endpoints.length} endpoints.`);
};

main();
